### ISSUE TITLE
iconize:IconButton doesn't work 

### ISSUE THREAD

**Issue by lecniers** [jsmarcus/Xamarin.Plugins#1]
I tried to use the iconize:IconButton but didn't find any sample so I looked at the code and I don't see anything added to the regular Button. I checked the Mateial version:  <mi:IconButton Icon="ic_check_circle" and think the iconize one should have the same binding property ?

great work, thanks.

**Comment by jsmarcus** [comment]
I am planning on getting some documentation together but it's basically a port of Iconify. So to add an icon (or more than one) you just put it in the text. Ex: "{fa-500px} 500px"

See Iconify here: http://joanzapata.com/android-iconify/

**Comment by lecniers** [comment]
I tried that one and others combinations several times without success;

 <iconize:IconButton Text="{fa-500px} 500px" />
 above code throw this: System.Exception: Expression must end with '}'

this code doesn't fail at compile time but just print:  {fa-500px} 500px and desired is to replace {fa-500px} for font icon:
<iconize:IconButton Text="{}{fa-500px} 500px" />
<iconize:IconButton Text="{Binding Key, StringFormat='{}{{{0}}} {0}'}" />
<iconize:IconButton Text="{Binding Key, StringFormat='{{{0}}} {0}'}" />

**Comment by lecniers** [comment]
Tried to pass text from ViewModel fail too:

xaml: <iconize:IconButton  Text="{Binding TestIcon}" />
ViewModel: TestIcon = "{fa-500px} fa-500px";

**Comment by cklenk** [comment]
![image](https://cloud.githubusercontent.com/assets/12185742/21434459/9f97aabc-c842-11e6-9be6-cf282135e1bb.png)

I too wrapped the font key in brackets and this is the final output.

**Comment by jsmarcus** [comment]
The library no longer works in that manner. I hope to provide a future update to bring that functionality back.

**Comment by thedracle** [comment]
How do you add an Icon to a button in the current implementation then?

**Comment by jsmarcus** [comment]
`<iconize:IconButton Text="fa-lock" />`

**Comment by thedracle** [comment]
Maybe this will save someone else the trouble- and I don't want to create an issue because it's not an issue with Iconize, but I spent a good chunk of yesterday figuring out that using any of the Themes that Xamarin is currently previewing interferes with Iconize.

It pretty much prevents any Font from replacing the Theme font- even if done programmatically.

Just a heads up for anyone else that runs up on this issue- and thinks it may have to do with their configuration or some missing step.

https://developer.xamarin.com/guides/xamarin-forms/themes/

**Comment by AlbertoMonteiro** [comment]
@jsmarcus I cant use IconButton with a custom text inside?

**Comment by kgbuddhima** [comment]
use **fas** instead of **fa**
`<iconize:IconButton Text="fas-info-circle"/>`
